# Generated by Django 6.0.7 on 2026-07-26 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract'), ('remote', 'Remote')], max_length=20)),
                ('location', models.CharField(max_length=150)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('minimum_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('skills', models.CharField(blank=True, max_length=500)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('number_of_vacancies', models.PositiveIntegerField(default=1)),
                ('work_mode', models.CharField(blank=True, max_length=50)),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('benefits', models.CharField(blank=True, max_length=500)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
